name: Build APK (debug)
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: ${{ runner.temp }}/android-sdk
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip wget

      - name: Install Android command line tools and SDK
        run: |
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O /tmp/cmdline.zip
          unzip /tmp/cmdline.zip -d $ANDROID_SDK_ROOT/cmdline-tools
          mkdir -p $ANDROID_SDK_ROOT/licenses
          yes | $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Download Gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-7.5.1-bin.zip -O gradle.zip
          unzip gradle.zip -d $HOME/gradle
          echo "$HOME/gradle/gradle-7.5.1/bin" >> $GITHUB_PATH

      - name: Build debug APK
        run: |
          export ANDROID_SDK_ROOT=${{ runner.temp }}/android-sdk
          ./gradlew assembleDebug || gradle assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
